spring:
    h2:
        console:
            enabled: true

    datasource:
      url: jdbc:mariadb://localhost:3306/gobook?currentSchema=gobook&createDatabaseIfNotExist=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: root
    jpa:
        hibernate:
            ddl-auto: update
#        properties:
#            hibernate:
#                format_sql: true
#                show_sql: true
        defer-datasource-initialization: true
#        database-platform: org.hibernate.dialect.H2Dialect


    servlet:
        multipart:
            maxFileSize: 20MB
            maxRequestSize: 100MB

itemImgLocation: /Users/ijingyu/upload/gobook/item # C:/shop/item
uploadPath: file:///Users/ijingyu/upload/gobook/  #file:///C:/shop/
